targets:
  $default:
    builders:
      factory:
        options:
          throw_on_missing_default_value: true
        enabled: true
        generate_for:
          include:
            - example/main.dart
            - example/*
            - test/integration/*
            - test/integration/**/*

builders:
  factory:
    import: "package:factory/factory_builder.dart"
    required_inputs: [".freezed.dart", ".g.dart"]
    builder_factories: ["factory"]
    build_extensions: { ".dart": [".factory.dart"] }
    auto_apply: dependents
    build_to: source