name: factory
description: factory generator package. Use it to generate factories implementations.
version: 1.0.0
publish_to: none
homepage: https://github.com/rIIh/factory_dart.git
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.0.0
  build: ^2.0.0
  build_config: ^1.0.0
  code_builder: ^4.0.0
  collection: ^1.0.0
  dart_style: ^2.0.0
  factory_annotation:
    git:
      url: https://github.com/rIIh/factory_dart.git
      path: factory_annotation
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  faker: ^2.0.0
  lints: ^1.0.0
  matcher: ^0.12.0
  source_gen_test: ^1.0.0
  test: ^1.0.0
  meta: ^1.0.0
