name: factory
description: factory generator package. Use it to generate factories implementations.
version: 2.1.0
homepage: https://github.com/rIIh/factory_dart
repository: https://github.com/rIIh/factory_dart.git
issue_tracker: https://github.com/rIIh/factory_dart/issues
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^5.0.0
  build: ^2.0.0
  build_config: ^1.0.0
  code_builder: ^4.0.0
  collection: ^1.0.0
  dart_style: ^2.0.0
  factory_annotation: ^2.0.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  faker: ^2.0.0
  lints: ^2.0.0
  matcher: ^0.12.0
  source_gen_test: ^1.0.0
  test: ^1.0.0
  meta: ^1.0.0
