name: sandbox
description: A sample command-line application.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  factory_annotation: 2.2.0

dev_dependencies:
  build_runner: any
  factory: ^2.2.0
  lints: ^4.0.0
  test: ^1.24.0
