name: factory_boy_generator
description: factory boy generator package. Use it to generate factories implementations.
version: 1.0.0
publish_to: none
homepage: https://github.com/rIIh/factory_boy_dart.git
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.0.0
  source_gen: ^1.0.0
  build: ^2.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0
  factory_boy:
    git:
      url: https://github.com/rIIh/factory_boy_dart.git
      path: factory_boy

dev_dependencies:
  faker: ^2.0.0
  lints: ^1.0.0
  test: ^1.0.0
