name: factory_annotation
description: Implementation details of factory package. Use it to declare factories for your project.
version: 1.0.0
publish_to: none
homepage: https://github.com/rIIh/factory_dart.git
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  faker: ^2.0.0
  test: ^1.0.0
  build_runner: ^2.0.0
  pedantic: ^1.0.0

dependencies:
  meta: ^1.0.0
